"""add_composite_indexes

Revision ID: b04e4c16f1ae
Revises: 4310c5e1c520
Create Date: 2026-06-23 23:26:14.995513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b04e4c16f1ae'
down_revision: Union[str, None] = '4310c5e1c520'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_plan_subtasks_plan_status', 'plan_subtasks', ['thread_task_plan_id', 'status'], unique=False)
    op.create_index('ix_thread_messages_task_type', 'thread_messages', ['thread_task_id', 'thread_chat_type'], unique=False)
    op.create_index('ix_thread_messages_thread_created', 'thread_messages', ['thread_id', 'created_at'], unique=False)
    op.create_index('ix_thread_tasks_thread_status', 'thread_tasks', ['thread_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_thread_tasks_thread_status', table_name='thread_tasks')
    op.drop_index('ix_thread_messages_thread_created', table_name='thread_messages')
    op.drop_index('ix_thread_messages_task_type', table_name='thread_messages')
    op.drop_index('ix_plan_subtasks_plan_status', table_name='plan_subtasks')
    # ### end Alembic commands ###
